---
- name: Converge
  hosts: key
  tasks:
    - name: Update APT
      apt:
        update_cache: yes
        upgrade: full
      when: ansible_os_family in ["Debian"]
    
    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
      when: ansible_os_family in ["Debian"]

    - name: Reboot if required
      reboot:
      when: 
        - reboot_required_file.stat.exists == true
        - ansible_os_family in ["Debian"]

    - name: Instal yum-utils
      yum:
        name: "yum-utils"
      when: ansible_os_family in ["RedHat"]

    - name: Update Zypper
      zypper:
        name: "*"
      when: ansible_os_family in ["Suse"]

    - name: Update RHEL
      yum:
        name: "*"
      when: ansible_os_family in ["RedHat"]

    - name: Register reboot status RHEL
      shell: "needs-restarting -r"
      register: rebooting
      when: ansible_os_family in ["RedHat"]

    - name: Reboot if required RHEL
      reboot:
      when:
        - ansible_os_family in ["RedHat"]
        - rebooting is failed
    


  
      

      