---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: Remove APT cache
      file:
        path: /var/cache/apt
        state: absent

    - name: Update APT
      apt:
        update_cache: yes
        upgrade: safe
        autoremove: yes
      when: ansible_os_family in ["Debian"]
    
    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
      when: ansible_os_family in ["Debian"]
      tags: 
        - reboot

    - name: Reboot if required
      reboot:
      when: 
        - ansible_os_family in ["Debian"]
        - reboot_required_file.stat.exists == true
      tags: 
        - reboot

    - name: Update RHEL
      dnf:
        name: "*"
        state: latest
      when: ansible_os_family in ["RedHat"]

    - name: Update SUSE
      community.general.zypper:
        name: "*"
        state: latest
      when: ansible_os_family in ["Suse"]

    - name: Install lsof for reboot check
      community.general.zypper:
        name: "lsof"
        state: latest
      when: ansible_os_family in ["Suse"]

    - name: Register reboot status RHEL
      shell: "dnf needs-restarting -r"
      register: rebooting
      ignore_errors: yes
      when: ansible_os_family in ["RedHat"]
      tags: 
        - reboot

    - name: Reboot if required RHEL
      reboot:
      when:
        - ansible_os_family in ["RedHat"]
        - rebooting is failed
      tags: 
        - reboot
    
    - name: Register reboot status SUSE
      shell: "zypper ps -s"
      register: rebootingSUSE
      when: ansible_os_family in ["Suse"]
      tags: 
        - reboot

    - name: Reboot if required SUSE
      reboot:
      when:
        - ansible_os_family in ["Suse"]
        - not rebootingSUSE.stdout is search("Reboot is probably not necessary")
      tags: 
        - reboot

  
      

      