---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: Update APT
      apt:
        update_cache: yes
        upgrade: full
      when: ansible_os_family in ["Debian"]
    
    - name: Check if reboot required
      stat:
        path: /var/run/reboot-required
      register: reboot_required_file
      when: ansible_os_family in ["Debian"]

    - name: Reboot if required
      reboot:
      when: 
        - ansible_os_family in ["Debian"]
        - reboot_required_file.stat.exists == true

    - name: Update RHEL
      dnf:
        name: "*"
        state: latest
      when: ansible_os_family in ["RedHat"]

    - name: Register reboot status RHEL
      shell: "dnf needs-restarting -r"
      register: rebooting
      ignore_errors: yes
      when: ansible_os_family in ["RedHat"]

    - name: Reboot if required RHEL
      reboot:
      when:
        - ansible_os_family in ["RedHat"]
        - rebooting is failed
    


  
      

      